package org.nikita.jdbctask.dto;

import java.io.Serializable;

/**
 * Data Transfer Object for OrderApproval entity
 */
public class OrderApprovalDTO implements Serializable {
    private long id;
    private final OrderDetailDTO orderDetail;

    /**
     * Constructor for inserting into a database. ID is autogenerated in the database
     */
    public OrderApprovalDTO (OrderDetailDTO orderDetail){
        this.orderDetail = orderDetail;
    }

    /**
     * Constructor for retrieving from a database
     */
    public OrderApprovalDTO (long id, OrderDetailDTO orderDetail){
        this(orderDetail);
        this.id = id;
    }

    @Override
    public String toString(){
        return "OrderApproval{" +
                "\nid: " + this.id +
                ",\norderDetail: " + this.orderDetail + "\n} ";
    }

    public OrderDetailDTO getOrderDetail() {
        return orderDetail;
    }

    public long getId() {
        return id;
    }
}
