package org.nikita.jdbctask.dto;

import org.nikita.jdbctask.enums.OrderStatus;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

/**
 * Data Transfer Object for OrderDetail entity
 */
public class OrderDetailDTO implements Serializable {
    private long id;
    private final OrderStatus orderStatus;
    private final List<ProductDTO> products;
    private final BigDecimal totalAmount;

    /**
     * Constructor for inserting into a database. ID is autogenerated in the database
     */
    public OrderDetailDTO(OrderStatus orderStatus, List<ProductDTO> products, BigDecimal totalAmount) {
        this.orderStatus = orderStatus;
        this.products = products;
        this.totalAmount = totalAmount;
    }

    /**
     * Constructor for retrieving from a database
     */
    public OrderDetailDTO(Long id, OrderStatus orderStatus, List<ProductDTO> products, BigDecimal totalAmount) {
        this(orderStatus, products, totalAmount);
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder productString = new StringBuilder();
        for (ProductDTO product : products) {
            productString.append(product.toString()).append(" ");
        }

        return "OrderDetail:{" +
                "\n\tid: " + id +
                ",\n\torderStatus: " + orderStatus +
                ",\n\tproducts: \n" + productString +
                ",\n\ttotalAmount: " + totalAmount.toString() + "\n} ";
    }

    public long getId() {
        return id;
    }

    public OrderStatus getOrderStatus() {
        return orderStatus;
    }

    public List<ProductDTO> getProducts() {
        return products;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }
}
